AVRDUDESSH_DIR ?= C:/Program Files (x86)/PuTTY/

AVRDUDESSH_REMOTE ?= user@remotehost

SSH ?= "$(AVRDUDESSH_DIR)plink"
SCP ?= "$(AVRDUDESSH_DIR)pscp"

# TODO: Rewrite this crap


AVRDUDESSH_AVRDUDE ?= $(AVRDUDE)

AVRDUDESSH_PROGRAMMER ?= $(AVRDUDE_PROGRAMMER)

# Set these in YOUR makefile
#AVRDUDE_PORT = USB
#AVRDUDE_PORT = /dev/ttyUSB0
#AVRDUDE_PORT = COM29

#AVRDUDE_BITCLOCK = 10
#AVRDUDE_BITCLOCK = 1

#AVRDUDE_BAUD = 57600

AVRDUDESSH_HEX ?= $(TARGET).hex

AVRDUDESSH_WRITE_FLASH ?= -U flash:w:$(AVRDUDESSH_HEX)

AVRDUDESSH_FLAGS_REQUIRED ?= -p $(MCU) -c $(AVRDUDESSH_PROGRAMMER)

AVRDUDESSH_FLAGS_STANDARD ?=

ifdef AVRDUDE_BITCLOCK
AVRDUDESSH_BITCLOCK ?= $(AVRDUDE_BITCLOCK)
endif

ifdef AVRDUDE_BAUD
AVRDUDESSH_BAUD ?= $(AVRDUDE_BAUD)
endif

ifdef AVRDUDE_PORT
AVRDUDESSH_PORT ?= $(AVRDUDE_PORT)
endif

ifdef AVRDUDESSH_BITCLOCK
AVRDUDESSH_FLAGS_AUTO += -B $(AVRDUDESSH_BITCLOCK)
endif

ifdef AVRDUDESSH_BAUD
AVRDUDESSH_FLAGS_AUTO += -b $(AVRDUDESSH_BAUD)
endif

ifdef AVRDUDESSH_PORT
AVRDUDESSH_FLAGS_AUTO += -P $(AVRDUDESSH_PORT)
endif

AVRDUDESSH_FLAGS_BASE ?= $(AVRDUDESSH_FLAGS_REQUIRED) $(AVRDUDESSH_FLAGS_STANDARD) $(AVRDUDESSH_FLAGS_AUTO)

ssh-copy: $(OUT_HEX)
	$(SCP) $(OUT_HEX) $(AVRDUDESSH_REMOTE):$(AVRDUDESSH_HEX)

ssh-test:
	$(SSH) $(AVRDUDESSH_REMOTE) $(AVRDUDESSH_AVRDUDE) $(AVRDUDESSH_FLAGS_BASE)

# Program the device.
ssh-flash: ssh-copy
	$(SSH) $(AVRDUDESSH_REMOTE) $(AVRDUDESSH_AVRDUDE) $(AVRDUDESSH_FLAGS_BASE) $(AVRDUDESSH_WRITE_FLASH)

.PHONY: ssh-flash ssh-test ssh-copy
