

LUFA_BASEDIR ?= ../LUFA/

ARCH ?= AVR8
LUFA_PATH ?= LUFA
include $(LUFA_BASEDIR)LUFA/Build/lufa_sources.mk

# Relative to LUFA_BASEDIR
LUFA_SRC ?= $(LUFA_SRC_USB) $(LUFA_SRC_USBCLASS) $(LUFA_SRC_PLATFORM)

LUFA_AR ?= LUFA.a

LUFA_OBJS ?= $(LUFA_SRC:%=$(BLD_DIR)%.o)

LUFA_OUT ?= $(BLD_LIBDIR)$(LUFA_AR)

F_USB ?= $(F_CPU)

AUTO_DEF += ARCH=ARCH_$(ARCH) F_USB=$(F_USB)

AUTO_LIB += $(LUFA_OUT)

LUFA_TARGET ?= LUFA

##### Targets

$(BLD_DIR)%.c.o: $(LUFA_BASEDIR)%.c
	$(ECO) "LUFA	$@"
	$(BLD_GCC) $< -o $@ -c $(BLD_GCCFLAGS_FINAL)

$(LUFA_OUT): $(LUFA_OBJS)
	$(ECO) "AR	$@"
	$(BLD_ARR) $@ $(LUFA_OBJS)

$(LUFA_OUT) $(LUFA_OBJS): $(MAKEFILE_LIST)

$(LUFA_TARGET): $(LUFA_OUT)

.PHONY: $(LUFA_TARGET)
.PRECIOUS: $(LUFA_OBJS)
.SECONDARY: $(LUFA_OUT)

# Explicitly include all our build dep files
LUFA_DEPFILES ?= $(LUFA_OBJS:$(BLD_DIR)%=$(BLD_DEPDIR)%.d)
-include $(LUFA_DEPFILES)

AUTO_GENERATED_FILES += $(LUFA_OUT) $(LUFA_OBJS) $(LUFA_DEPFILES)
