
LUFA_DIR ?= ../LUFA/

LUFA_MAKEFILE         ?= LUFA/Build/lufa_build.mk
LUFA_MAKEFILE_SOURCES ?= $(LUFA_DIR)LUFA/Build/lufa_sources.mk

LUFA_MAKE_EXTRA_OPTS ?= 

LUFA_MAKE_BASE_OPTS ?= -s -C $(LUFA_DIR) -f $(LUFA_MAKEFILE) ARCH=$(ARCH) LUFA_PATH=LUFA

ARCH ?= AVR8
LUFA_PATH ?= LUFA
include $(LUFA_MAKEFILE_SOURCES)

LUFA_SRC ?= $(LUFA_SRC_USB) $(LUFA_SRC_USBCLASS) $(LUFA_SRC_PLATFORM)

# We really need the quoted version since we pass it on to LUFA's build as an argument
LUFA_SRC_QT ?= "$(LUFA_SRC)"

LUFA_BLDDIR ?= $(BLDDIR)LUFA/

LUFA_BLDDIR_ABS ?= "$(abspath $(LUFA_BLDDIR))/"

# Remove the "UL" that LUFA sets on its own
LUFA_F_CPU ?= $(F_CPU:UL=)
LUFA_F_USB ?= $(F_USB:UL=)
	
LUFA_TARGET ?= $(TARGET)_LUFA
LUFA_MCU ?= $(MCU)
LUFA_OBJDIR ?= $(LUFA_BLDDIR_ABS)

LUFA_MAKE_OPTS ?= $(LUFA_MAKE_BASE_OPTS) \
 TARGET=$(LUFA_TARGET) MCU=$(LUFA_MCU) SRC=$(LUFA_SRC_QT) \
 F_CPU=$(LUFA_F_CPU) F_USB=$(LUFA_F_USB) \
 OBJDIR=$(LUFA_OBJDIR) $(LUFA_MAKE_EXTRA_OPTS)

LUFA_MAKE_TARGET ?= "$(abspath $(LUFA_OUTPUT_AR))"

LUFA_OUTPUT_AR ?= $(LIBDIR)$(LUFA_AR_FILENAME)

LUFA_AR_FILENAME ?= LUFA.a

LUFA_MAKE ?= "$(MAKE)"

AUTO_LIB += $(LUFA_AR_FILENAME)
AUTO_INC += $(LUFA_DIR)

LUFA_LOCAL_TARGET_DEPS ?= $(MAKEFILE_LIST)

# LUFA doesn't make its own build dir....
LUFA_LOCAL_TARGET_ORDER_DEPS ?= $(LIBDIR) $(LUFA_BUILD_DIR_TARGET)

# The var $(LUFA_BUILD_DIR_TARGET) holds the literal string 'LUFA_BUILD_DIR_TARGET'
LUFA_BUILD_DIR_TARGET ?= LUFA_BUILD_DIR_TARGET

# We need an extra target just for LUFA's build dir
$(LUFA_BUILD_DIR_TARGET):
	$(MKD) $(LUFA_BLDDIR_ABS)

$(LUFA_OUTPUT_AR): $(LUFA_LOCAL_TARGET_DEPS) | $(LUFA_LOCAL_TARGET_ORDER_DEPS)
	$(ECO) "Lib: $@"
	$(LUFA_MAKE) $(LUFA_MAKE_OPTS) $(LUFA_MAKE_TARGET)

clean: clean_lufa

lufa: $(LUFA_OUTPUT_AR)

clean_lufa:
	$(ECO) Cleaning LUFA...
	$(LUFA_MAKE) $(LUFA_MAKE_BASE_OPTS) TARGET=$(LUFA_TARGET) MCU=$(LUFA_MCU) SRC=$(LUFA_SRC_QT) F_USB=$(LUFA_F_USB) clean

.PHONY: clean_lufa clean lufa $(LUFA_BUILD_DIR_TARGET)
