


NRF51_SRCDIR ?= $(NRF51_BASEDIR)components/

# This matches the folder name that Nordic assigns
NRF51_BLE ?= ble

NRF51_BLE_SRCDIR ?= $(NRF51_SRCDIR)$(NRF51_BLE)/

NRF51_BLE_BLDDIR ?= $(BLD_DIR)nRF51/$(NRF51_BLE)/

# Names of nRF51 source files to "find" and include
NRF51_BLE_C ?= ble_advdata

NRF51_BLE_SRC_FILES ?= $(NRF51_BLE_C:%=%.c)

NRF51_BLE_SRC_FILES_FULL ?= $(foreach file,$(NRF51_BLE_SRC_FILES),$(shell find $(NRF51_BLE_SRCDIR) -type f -name $(file)))

NRF51_BLE_AR ?= nRF51-$(NRF51_BLE).a

NRF51_BLE_OBJS ?= $(NRF51_BLE_SRC_FILES_FULL:$(NRF51_BLE_SRCDIR)%=$(NRF51_BLE_BLDDIR)%.o)

NRF51_BLE_OUT ?= $(BLD_LIBDIR)$(NRF51_BLE_AR)

NRF51_BLE_GCCFLAGS_FINAL ?= $(BLD_GCCFLAGS_FINAL) $(NRF51_BLE_GCCFLAGS_EXTRA)

NRF51_BLE_INCLUDES ?= $(sort $(dir $(NRF51_BLE_SRC_FILES_FULL)))

AUTO_INC += $(NRF51_BLE_INCLUDES)

AUTO_LIB += $(NRF51_BLE_OUT)

NRF51_BLE_TARGET ?= nRF51/BLE

AUTO_GENERATED_FILES += $(NRF51_BLE_OUT) $(NRF51_BLE_OBJS) $(NRF51_BLE_DEPFILES)

##### Targets

$(NRF51_BLE_BLDDIR)%.c.o: $(NRF51_BLE_SRCDIR)%.c
	$(ECO) "nRF51 C	$@"
	$(BLD_GCC) $< -o $@ -c $(NRF51_BLE_GCCFLAGS_FINAL)

$(NRF51_BLE_OUT): $(NRF51_BLE_OBJS)
	$(ECO) "nRF51 AR	$@"
	$(BLD_ARR) $@ $(NRF51_BLE_OBJS)

$(NRF51_BLE_OUT) $(NRF51_BLE_OBJS): | $(MAKEFILE_LIST)

$(NRF51_BLE_TARGET): $(NRF51_BLE_OUT)

.PHONY: $(NRF51_BLE_TARGET)
.PRECIOUS: $(NRF51_BLE_OBJS)
.SECONDARY: $(NRF51_BLE_OUT)

# Explicitly include all our build dep files
NRF51_BLE_DEPFILES = $(NRF51_BLE_OBJS:$(BLD_DIR)%=$(BLD_DEPDIR)%.d)
-include $(NRF51_BLE_DEPFILES)
