


nRF51SDK_SourcePath ?= $(nRF51SDK_BasePath)components/

# This matches the folder name that Nordic assigns
NRF51_NRFDRIVERS ?= drivers_nrf

NRF51_NRFDRIVERS_SRCDIR ?= $(nRF51SDK_SourcePath)$(NRF51_NRFDRIVERS)/

NRF51_NRFDRIVERS_BLDDIR ?= $(Build_Path)nRF51/$(NRF51_NRFDRIVERS)/

# Names of nRF51 source files to "find" and include
NRF51_NRFDRIVERS_C ?= *

NRF51_NRFDRIVERS_SRC_FILES ?= $(NRF51_NRFDRIVERS_C:%=%.c)

# Filter sources that depend on user boards.h
NRF51_NRFDRIVERS_SRC_USERBOARDS_FILTER ?= %spi_master/spi_5W_master.c

# If the user isn't using an BLE soft device, don't build pstorage
ifeq (,$(filter $(NRF51_SOFTDEVICE_VERSION),s110 s120 s130 s210 s310))
 NRF51_NRFDRIVERS_SRC_FILES_AUTO_FILTER += %pstorage/pstorage.c
endif

# Filter certain sources by default
NRF51_NRFDRIVERS_SRC_FILES_FILTER ?= $(NRF51_NRFDRIVERS_SRC_USERBOARDS_FILTER) $(NRF51_NRFDRIVERS_SRC_FILES_AUTO_FILTER)

NRF51_NRFDRIVERS_SRC_FILES_FULL ?= $(filter-out $(NRF51_NRFDRIVERS_SRC_FILES_FILTER),$(foreach file,$(NRF51_NRFDRIVERS_SRC_FILES),$(shell find $(NRF51_NRFDRIVERS_SRCDIR) -type f -name "$(file)")))

NRF51_NRFDRIVERS_AR ?= nRF51-$(NRF51_NRFDRIVERS).a

NRF51_NRFDRIVERS_OBJS ?= $(NRF51_NRFDRIVERS_SRC_FILES_FULL:$(NRF51_NRFDRIVERS_SRCDIR)%=$(NRF51_NRFDRIVERS_BLDDIR)%.o)

NRF51_NRFDRIVERS_OUT ?= $(BLD_LIBDIR)$(NRF51_NRFDRIVERS_AR)

NRF51_NRFDRIVERS_GCCFLAGS_FINAL ?= $(BLD_GCCFLAGS_FINAL) $(NRF51_NRFDRIVERS_GCCFLAGS_EXTRA)

AUTO_LIB += $(NRF51_NRFDRIVERS_OUT)

NRF51_NRFDRIVERS_TARGET ?= nRF51/nRF_Drivers

AUTO_GENERATED_FILES += $(NRF51_NRFDRIVERS_OUT) $(NRF51_NRFDRIVERS_OBJS) $(NRF51_NRFDRIVERS_DEPFILES)

##### Targets

$(NRF51_NRFDRIVERS_BLDDIR)%.c.o: $(NRF51_NRFDRIVERS_SRCDIR)%.c
	$(ECO) "nRF51 C	$@"
	$(BLD_GCC) $< -o $@ -c $(NRF51_NRFDRIVERS_GCCFLAGS_FINAL)

$(NRF51_NRFDRIVERS_OUT): $(NRF51_NRFDRIVERS_OBJS)
	$(ECO) "nRF51 AR	$@"
	$(BLD_ARR) $@ $(NRF51_NRFDRIVERS_OBJS)

$(NRF51_NRFDRIVERS_OUT) $(NRF51_NRFDRIVERS_OBJS): $(MAKEFILE_LIST)

$(NRF51_NRFDRIVERS_TARGET): $(NRF51_NRFDRIVERS_OUT)

.PHONY: $(NRF51_NRFDRIVERS_TARGET)
.PRECIOUS: $(NRF51_NRFDRIVERS_OBJS)
.SECONDARY: $(NRF51_NRFDRIVERS_OUT)

# Explicitly include all our build dep files
NRF51_NRFDRIVERS_DEPFILES = $(NRF51_NRFDRIVERS_OBJS:$(Build_Path)%=$(BLD_DEPDIR)%.d)
-include $(NRF51_NRFDRIVERS_DEPFILES)
