


nRF51SDK_SourcePath ?= $(nRF51SDK_BasePath)components/

# This matches the folder name that Nordic assigns
NRF51_SOFTDEVICE ?= softdevice

NRF51_SOFTDEVICE_DIR ?= $(nRF51SDK_SourcePath)$(NRF51_SOFTDEVICE)/

NRF51_SOFTDEVICE_SRCDIR ?= $(NRF51_SOFTDEVICE_DIR)common/

NRF51_SOFTDEVICE_HEADER_INC ?= $(NRF51_SOFTDEVICE_VERSION)/headers

NRF51_SOFTDEVICE_BLDDIR ?= $(BLD_DIR)nRF51/$(NRF51_SOFTDEVICE)/

# Specifiy the folder name used for the soft device's header files
NRF51_SOFTDEVICE_VERSION ?= blank

NRF51_SOFTDEVICE_DEFINES ?= BLE_STACK_SUPPORT_REQD

ifneq ($(NRF51_SOFTDEVICE_VERSION),blank)
 # Names of nRF51 source files to "find" and include
 NRF51_SOFTDEVICE_C ?= softdevice_handler
endif

NRF51_SOFTDEVICE_SRC_FILES ?= $(NRF51_SOFTDEVICE_C:%=%.c)

NRF51_SOFTDEVICE_SRC_FILES_FULL ?= $(foreach file,$(NRF51_SOFTDEVICE_SRC_FILES),$(shell find $(NRF51_SOFTDEVICE_SRCDIR) -type f -name "$(file)"))

NRF51_SOFTDEVICE_AR ?= nRF51-$(NRF51_SOFTDEVICE).a

NRF51_SOFTDEVICE_OBJS ?= $(NRF51_SOFTDEVICE_SRC_FILES_FULL:$(NRF51_SOFTDEVICE_SRCDIR)%=$(NRF51_SOFTDEVICE_BLDDIR)%.o)

NRF51_SOFTDEVICE_OUT ?= $(BLD_LIBDIR)$(NRF51_SOFTDEVICE_AR)

#NRF51_SOFTDEVICE_D_FLAGS ?= $(NRF51_SOFTDEVICE_DEFINES:%=-D%)

NRF51_SOFTDEVICE_GCCFLAGS_EXTRA ?= $(NRF51_SOFTDEVICE_D_FLAGS)

NRF51_SOFTDEVICE_GCCFLAGS_FINAL ?= $(BLD_GCCFLAGS_FINAL) $(NRF51_SOFTDEVICE_GCCFLAGS_EXTRA)

NRF51_SOFTDEVICE_HEADERS_FULL ?= $(NRF51_SOFTDEVICE_DIR)$(NRF51_SOFTDEVICE_HEADER_INC)

NRF51_SOFTDEVICE_INCLUDES ?= $(NRF51_SOFTDEVICE_HEADERS_FULL) $(sort $(dir $(NRF51_SOFTDEVICE_SRC_FILES_FULL)))

# BUGFIX: Soft device header files take precedence
AUTO_INC := $(NRF51_SOFTDEVICE_INCLUDES) $(AUTO_INC)

AUTO_LIB += $(NRF51_SOFTDEVICE_OUT)

AUTO_DEF += $(NRF51_SOFTDEVICE_DEFINES)

NRF51_SOFTDEVICE_TARGET ?= nRF51/softdevice

AUTO_GENERATED_FILES += $(NRF51_SOFTDEVICE_OUT) $(NRF51_SOFTDEVICE_OBJS) $(NRF51_SOFTDEVICE_DEPFILES)

##### Targets

$(NRF51_SOFTDEVICE_BLDDIR)%.c.o: $(NRF51_SOFTDEVICE_SRCDIR)%.c
	$(ECO) "nRF51 C	$@"
	$(BLD_GCC) $< -o $@ -c $(NRF51_SOFTDEVICE_GCCFLAGS_FINAL)

$(NRF51_SOFTDEVICE_OUT): $(NRF51_SOFTDEVICE_OBJS)
	$(ECO) "nRF51 AR	$@"
	$(BLD_ARR) $@ $(NRF51_SOFTDEVICE_OBJS)

$(NRF51_SOFTDEVICE_OUT) $(NRF51_SOFTDEVICE_OBJS): $(MAKEFILE_LIST)

$(NRF51_SOFTDEVICE_TARGET): $(NRF51_SOFTDEVICE_OUT)

.PHONY: $(NRF51_SOFTDEVICE_TARGET)
.PRECIOUS: $(NRF51_SOFTDEVICE_OBJS)
.SECONDARY: $(NRF51_SOFTDEVICE_OUT)

# Explicitly include all our build dep files
NRF51_SOFTDEVICE_DEPFILES = $(NRF51_SOFTDEVICE_OBJS:$(BLD_DIR)%=$(BLD_DEPDIR)%.d)
-include $(NRF51_SOFTDEVICE_DEPFILES)
